name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag for the release (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release title'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
          files: |
            asciiviz
